development:
     host: localhost
     adapter: mysql
     database: fedenasch
     port: 3306
     username: root
     password: 

test: &test
     host: localhost
     adapter: mysql
     database: fedenasch
     port: 3306
     username: root
     password: 

production:
     host: localhost
     adapter: mysql
     database: fedenasch
     port: 3306
     username: root
     password: 
cucumber:
 <<: *test
